### ISSUE TITLE
frameworks/base on 0.9.10-ALPHA

### ISSUE THREAD

**Issue by joknu1** [pvoid/AndroidBlueprintPlugin#17]
```
Java.lang.AssertionError: Empty blueprints list
	at com.github.pvoid.androidbp.module.android.BlueprintSourceProviders.<init>(BlueprintSourceProviders.kt:30)
	at com.github.pvoid.androidbp.module.android.AospAndroidProjectSystem$sourceProvidersFactory$1.createSourceProvidersFor(AospProjectSystemProvider.kt:76)
	at com.android.tools.idea.projectsystem.SourceProvidersKt.createSourceProviderFor(SourceProviders.kt:205)
	at com.android.tools.idea.projectsystem.SourceProvidersKt.getSourceProviders(SourceProviders.kt:198)
	at com.android.tools.idea.projectsystem.SourceProviders$Companion.getInstance(SourceProviders.kt:128)
	at com.android.tools.idea.res.IdeResourcesUtil.isLocalResourceDirectoryInAnyVariant(IdeResourcesUtil.kt:1708)
	at com.android.tools.idea.res.IdeResourcesUtil.isResourceDirectory(IdeResourcesUtil.kt:1775)
	at com.android.tools.idea.res.IdeResourcesUtil.isResourceSubdirectory(IdeResourcesUtil.kt:1753)
	at com.android.tools.idea.res.IdeResourcesUtil.isInResourceSubdirectoryInAnyVariant(IdeResourcesUtil.kt:1726)
	at org.jetbrains.android.dom.AndroidXmlExtension$2.compute(AndroidXmlExtension.java:103)
	at org.jetbrains.android.dom.AndroidXmlExtension$2.compute(AndroidXmlExtension.java:99)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at org.jetbrains.android.dom.AndroidXmlExtension.isAvailable(AndroidXmlExtension.java:99)
	at com.intellij.xml.XmlExtension.calcExtension(XmlExtension.java:60)
	at com.intellij.xml.XmlExtension.lambda$getExtension$0(XmlExtension.java:43)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.xml.XmlExtension.getExtension(XmlExtension.java:43)
	at com.intellij.xml.XmlExtension.getExtensionByElement(XmlExtension.java:70)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeNamespaceMap(XmlTagDelegate.java:788)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.lambda$getNamespaceMap$11(XmlTagDelegate.java:757)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNamespaceMap(XmlTagDelegate.java:756)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getPrefixByNamespace(XmlTagDelegate.java:714)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getPrefixByNamespace(XmlTagImpl.java:222)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getAttribute(XmlTagDelegate.java:649)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getAttribute(XmlTagImpl.java:192)
	at org.intellij.lang.xpath.xslt.XsltSupport$XsltSupportProvider.compute(XsltSupport.java:373)
	at org.intellij.lang.xpath.xslt.XsltSupport$XsltSupportProvider.compute(XsltSupport.java:350)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:46)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:82)
	at org.intellij.lang.xpath.xslt.XsltSupport.getXsltLanguageLevel(XsltSupport.java:242)
	at org.intellij.lang.xpath.xslt.XsltSupport.isXsltFile(XsltSupport.java:236)
	at org.intellij.lang.xpath.xslt.impl.XsltFormattingModelBuilder.isEngagedToFormat(XsltFormattingModelBuilder.java:49)
	at com.intellij.lang.LanguageFormatting.findCustomFormattingModelBuilder(LanguageFormatting.java:46)
	at com.intellij.lang.LanguageFormatting.forContext(LanguageFormatting.java:31)
	at com.intellij.lang.LanguageFormatting.forContext(LanguageFormatting.java:23)
	at com.intellij.psi.codeStyle.DetectableIndentOptionsProvider.isEnabled(DetectableIndentOptionsProvider.java:116)
	at com.intellij.psi.codeStyle.DetectableIndentOptionsProvider.getIndentOptions(DetectableIndentOptionsProvider.java:57)
	at com.intellij.psi.codeStyle.CodeStyleSettings.getIndentOptionsByFile(CodeStyleSettings.java:761)
	at com.intellij.application.options.CodeStyle.updateDocumentIndentOptions(CodeStyle.java:372)
	at com.intellij.openapi.editor.impl.SettingsImpl.reinitDocumentIndentOptions(SettingsImpl.java:372)
	at com.intellij.openapi.editor.impl.SettingsImpl.reinitSettings(SettingsImpl.java:353)
	at com.intellij.openapi.editor.impl.EditorImpl.reinitSettings(EditorImpl.java:957)
	at com.intellij.openapi.editor.impl.EditorImpl.reinitSettings(EditorImpl.java:940)
	at com.intellij.openapi.editor.impl.EditorImpl.setHighlighter(EditorImpl.java:1339)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.lambda$loadEditorInBackground$1(TextEditorImpl.java:77)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.lambda$loadEditorInBackground$0(PsiAwareTextEditorImpl.java:59)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.loadingFinished(AsyncEditorLoader.java:171)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$scheduleLoading$2(AsyncEditorLoader.java:119)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:577)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by pvoid** [comment]
Should be fixed now
